#!/usr/bin/env node
/**
 * Theme build script
 * Compiles theme folders into single CSS bundles:
 *   theme/player/<name>/theme.json  (+ optional style.css) -> theme/player.css
 *   theme/admin/<name>/theme.json   (+ optional style.css) -> theme/admin.css
 *
 * Usage: node theme/build.js
 */
const fs = require('fs');
const path = require('path');

const THEME_DIR = path.join(__dirname);
const OUT_PLAYER = path.join(THEME_DIR, 'player.css');
const OUT_ADMIN = path.join(THEME_DIR, 'admin.css');

function build(type) {
    const dir = path.join(THEME_DIR, type);
    if (!fs.existsSync(dir)) { console.log(`[build] ${type}/ not found, skip`); return null; }
    const names = fs.readdirSync(dir).filter(n => {
        return fs.statSync(path.join(dir, n)).isDirectory() && fs.existsSync(path.join(dir, n, 'theme.json'));
    });
    let css = '/* Auto-generated by theme/build.js - do not edit directly */\n';
    for (const name of names) {
        const tdir = path.join(dir, name);
        const json = JSON.parse(fs.readFileSync(path.join(tdir, 'theme.json'), 'utf8'));
        const id = json.id || name;
        const vars = json.variables || {};
        const varStr = Object.entries(vars).map(([k, v]) => {
            const key = k.startsWith('--') ? k : '--' + k;
            return `${key}:${v};`;
        }).join('');
        css += `[data-theme="${id}"]{${varStr}}\n`;
        const styleFile = path.join(tdir, 'style.css');
        if (fs.existsSync(styleFile)) {
            const style = fs.readFileSync(styleFile, 'utf8');
            css += `[data-theme="${id}"]{` + style.split('{').map((s, i) => i === 0 ? '' : s).join('{') + '}\n';
            // simpler: just append raw style.css content (it may contain nested selectors)
        }
    }
    const out = type === 'player' ? OUT_PLAYER : OUT_ADMIN;
    fs.writeFileSync(out, css);
    console.log(`[build] ${type}: ${names.length} themes -> ${path.basename(out)} (${css.length} bytes)`);
    return names;
}

// Rebuild style.css blocks properly: the naive approach above is broken for
// component css with nested selectors. Do a clean pass:
function build2(type) {
    const dir = path.join(THEME_DIR, type);
    if (!fs.existsSync(dir)) return null;
    const names = fs.readdirSync(dir).filter(n => {
        return fs.statSync(path.join(dir, n)).isDirectory() && fs.existsSync(path.join(dir, n, 'theme.json'));
    });
    let css = '/* Auto-generated by theme/build.js - do not edit directly */\n';
    for (const name of names) {
        const tdir = path.join(dir, name);
        const json = JSON.parse(fs.readFileSync(path.join(tdir, 'theme.json'), 'utf8'));
        const id = json.id || name;
        const vars = json.variables || {};
        const varStr = Object.entries(vars).map(([k, v]) => {
            const key = k.startsWith('--') ? k : '--' + k;
            return `${key}:${v};`;
        }).join('');
        css += `[data-theme="${id}"]{${varStr}}\n`;
        const styleFile = path.join(tdir, 'style.css');
        if (fs.existsSync(styleFile)) {
            // style.css contains selectors like ".card{...}" - prefix with theme scope
            const style = fs.readFileSync(styleFile, 'utf8');
            css += style.split('\n').map(line => {
                const trimmed = line.trim();
                if (!trimmed || trimmed.startsWith('/*')) return line;
                const braceIdx = trimmed.indexOf('{');
                if (braceIdx === -1) return line;
                const selector = trimmed.slice(0, braceIdx).trim();
                const rest = trimmed.slice(braceIdx);
                const scoped = selector.split(',').map(s => `[data-theme="${id}"] ${s.trim()}`).join(',');
                return `${scoped}${rest}`;
            }).join('\n') + '\n';
        }
    }
    const out = type === 'player' ? OUT_PLAYER : OUT_ADMIN;
    fs.writeFileSync(out, css);
    console.log(`[build] ${type}: ${names.length} themes -> ${path.basename(out)} (${css.length} bytes)`);
    return names;
}

build2('player');
build2('admin');
console.log('[build] done. Serve theme/player.css and theme/admin.css via /api/theme/player and /api/theme/admin');
